+ Strict bash by default

diff --git a/touch-exec b/touch-exec
--- a/touch-exec
+++ b/touch-exec
@@ -6,4 +6,7 @@ if [ $# -ne 1 ]; then
 fi
 
 echo "#!/bin/bash" > "$1"
+echo "" >> "$1"
+echo "set -euo pipefail" >> "$1"
+echo "IFS=$'\n\t'" >> "$1"
 chmod +x "$1"
